version: "3"
services:
  app-net-api:
    build: ./
    container_name: deploy-rapidp
    restart: always
    ports:
      - "9996:8080"
    networks:
      - jenking
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}

networks:
  jenking:
    driver: bridge