pipeline {
    agent any
    environment {
        CARPETA_APLICACION = './consultas-gis.api/consultas-gis.api'
        ASPNETCORE_ENVIRONMENT = 'Development'
    }

    stages {
        stage('Run docker compose') {
            steps {
                dir("${CARPETA_APLICACION}") {
                    //sh 'docker-compose up -d'
                    sh 'ls'
                }
                
            }
        }

        // stage('Run docker compose') {
        //     steps {
        //         echo "hola desde github"
        //     }
        // }

    }
}