[v1.1][20-10-2025]
Añadir clase Consulta y mejorar consultas SQL

* Se ha añadido la clase `Consulta` en `Consulta.cs` con propiedades serializables para JSON. 

* Se ha modificado el método `ObtenerPrueba` en `ConsultasController.cs` para devolver la fecha actual en formato `DateOnly`. 

* Además, se han ajustado las consultas SQL en `Repositorio.cs` para mejorar la lógica de obtención de datos y se han alineado las selecciones de columnas con las propiedades de la clase `Consulta`.